# Generated by Django 4.2.8 on 2024-02-17 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('FamilyApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='family_member_groups', related_query_name='family_member_group', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='familymember',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='familymember',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='family_member_permissions', related_query_name='family_member_permission', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
