# Generated by Django 4.2.8 on 2024-02-17 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FamilyApp', '0003_alter_familymember_groups_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familymember',
            options={'verbose_name': 'Family Member', 'verbose_name_plural': 'Family Members'},
        ),
    ]
