# Generated by Django 4.2.8 on 2024-02-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FamilyApp', '0004_alter_familymember_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
