# Generated by Django 4.2.8 on 2024-02-17 19:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FamilyApp', '0005_familymember_is_active_familymember_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='current_address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='date_of_birth',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='permanent_address',
            field=models.CharField(default='', max_length=255),
        ),
    ]
