# Generated by Django 4.2.8 on 2024-02-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FamilyApp', '0006_alter_familymember_current_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='is_alive',
            field=models.BooleanField(default=True),
        ),
    ]
