# Generated by Django 4.2.8 on 2024-02-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FamilyApp', '0007_familymember_is_alive'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='is_married',
            field=models.BooleanField(default=False),
        ),
    ]
