# Generated by Django 4.2.8 on 2024-02-20 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FamilyApp', '0008_familymember_is_married'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('Parent', 'Parent'), ('Spouse', 'Spouse')], max_length=100)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_relationships', to=settings.AUTH_USER_MODEL)),
                ('related_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='related_person_relationships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
