# Generated by Django 4.2.8 on 2024-02-21 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FamilyApp', '0009_relationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='person_relationships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='related_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_person_relationships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='relationship_type',
            field=models.CharField(choices=[('Parent', 'Parent'), ('Child', 'Child'), ('Spouse', 'Spouse'), ('Sibling', 'Sibling'), ('Grandparent', 'Grandparent'), ('Grandchild', 'Grandchild'), ('Aunt', 'Aunt'), ('Uncle', 'Uncle'), ('Cousin', 'Cousin'), ('Niece', 'Niece'), ('Nephew', 'Nephew'), ('In-Law', 'In-Law'), ('Step-Parent', 'Step-Parent'), ('Step-Child', 'Step-Child'), ('Half-Sibling', 'Half-Sibling')], max_length=100),
        ),
    ]
