# Generated by Django 4.2.8 on 2024-02-24 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FamilyApp', '0010_alter_relationship_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='date_of_death',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='facebook',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='familymember',
            name='instagram',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='familymember',
            name='linkedin',
            field=models.CharField(default='', max_length=255),
        ),
    ]
