# Generated by Django 4.2.8 on 2024-02-28 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FamilyApp', '0013_alter_relationship_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='person_relationships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='related_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_person_relationships', to=settings.AUTH_USER_MODEL),
        ),
    ]
