# Generated by Django 4.2.8 on 2025-01-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FamilyApp', '0014_alter_relationship_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
