# Generated by Django 4.2.8 on 2025-01-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FamilyApp', '0015_familymember_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
